### ISSUE TITLE
Invite all team members to repo

### ISSUE THREAD

**Issue by ugurdogrusoz** [NuruNabiyev/1F.PlanetInvasion#1]

**Comment by NuruNabiyev** [comment]
Done

**Comment by NuruNabiyev** [comment]
Done!

**Comment by ugurdogrusoz** [comment]
@NuruNabiyev did everybody join? If not please reopen the issue until they do so

**Comment by ugurdogrusoz** [comment]
@NuruNabiyev also, in general you should let the creator of the issue verify (whether the issue has been resolved) and close the issue

**Comment by NuruNabiyev** [comment]
@ugurdogrusoz Yes, everybody has joined this repo.
